//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Origin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysModule
    {
        public string ModuleId { get; set; }
        public string ModuleName { get; set; }
        public string ModuleNameEn { get; set; }
        public string ActionName { get; set; }
        public string ControllerName { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public string BtnId { get; set; }
        public string BtnClass { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> ModuleLevel { get; set; }
        public short IsDel { get; set; }
        public string ParentId { get; set; }
        public Nullable<int> ModuleType { get; set; }
        public Nullable<bool> IsDisplay { get; set; }
    }
}
